---
- set_fact:
    monaco_projects_folder: "{{ role_path }}/files/monaco/projects"

- name: Easytravel - Apply Monitoring as Code
  include_role:
    name: monaco
    tasks_from: apply-monaco
    apply:
      environment:
        HOST_GROUP_NAME: "{{ host_group }}"
  vars:
    monaco_project: "easytravel"
    monaco_projects_root: "{{ monaco_projects_folder }}" 
