---
- name: Install apt packages
  become: true
  become_user: root
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
    - haproxy

- become: true
  become_user: root
  copy:
    src: haproxy.cfg
    dest: /etc/haproxy/haproxy.cfg

- name: Enable service haproxy
  become: true
  become_user: root
  ansible.builtin.systemd:
    name: haproxy.service
    enabled: yes
    masked: no

- name: Ensure haproxy is running
  become: true
  become_user: root
  ansible.builtin.systemd:
    state: restarted
    name: haproxy
