---
- name: Install apt packages
  become: true
  become_user: root
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
    - openjdk-8-jre
    - apt-transport-https
    - software-properties-common
    - jq

- file:
    path: "{{ role_path }}/files"
    state: directory

- name: Download Easytravel installer
  get_url:
    url: "https://etinstallers.demoability.dynatracelabs.com/latest/dynatrace-easytravel-linux-x86_64.jar"
    dest: "{{ easytravel_classic_download_location }}"
    timeout: 300
  when: not easytravel_classic_download_location is exists

- name: Run installer
  block:
  - shell: 
      cmd: "java -jar {{ easytravel_classic_download_location }} -y"
      chdir: "{{ role_path }}/files"
    when: not easytravel_classic_install_location is exists
  - become: true
    become_user: root
    shell: 
      cmd: "/bin/bash installChromeDeps.sh"
      chdir: "{{ easytravel_classic_install_location }}/resources"
#   - shell: 
#       cmd: "sed -i 's|^config.apacheWebServerPort=8079|config.apacheWebServerPort=80|g' easyTravelConfig.properties"
#       chdir: "{{ easytravel_classic_install_location }}/resources"
#   - shell: 
#       cmd: "sed -i 's|^config.nginxWebServerPort=8079|config.nginxWebServerPort=80|g' easyTravelConfig.properties"
#       chdir: "{{ easytravel_classic_install_location }}/resources"
#   - shell: 
#       cmd: "sed -i 's|^config.weblauncherPort=8094|config.weblauncherPort=8080|g' easyTravelConfig.properties"
#       chdir: "{{ easytravel_classic_install_location }}/resources"
  - become: true
    become_user: root
    copy:
      content: |-
        [Unit]
        Description=easytravel launcher
        Requires=network-online.target
        After=network-online.target

        [Service]
        User={{ ace_box_user }}
        Group={{ ace_box_user }}
        Restart=on-failure
        ExecStart={{ easytravel_classic_install_location }}/weblauncher/weblauncher.sh
        ExecReload=/bin/kill -HUP $MAINPID

        [Install]
        WantedBy=multi-user.target
      dest: "/etc/systemd/system/easytravel.service"

- name: Enable service easytravel
  become: true
  become_user: root
  ansible.builtin.systemd:
    name: easytravel.service
    enabled: yes
    masked: no

- name: Make sure a easytravel is running
  become: true
  become_user: root
  ansible.builtin.systemd:
    state: started
    name: easytravel

# - name: Wait for Easytravel to be up
#   uri:
#     url: "http://localhost:8080/main"
#     status_code: 200
#     validate_certs: no
#   register: result
#   retries: 60
#   delay: 5
#   until: result.status == 200
