
config:
  - app-detect-easytravel-classic: "rule.json"
  
app-detect-easytravel-classic:
  - name: "projects/easytravel/application-web/app-easytravel-classic.name"
  - applicationId: "projects/easytravel/application-web/app-easytravel-classic.id"
  - pattern: "{{ .Env.HOST_IP }}"
